{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* DESIGN: Header START *}

{* get the sections list which consist of: sections allowed to assign to the object by the
   current loged in user, plus the section which is currently assigned to the object *}
{def $sections=$object.allowed_assign_section_list
     $currentSectionName='unknown'}

{* get the name of the object's current section *}
{foreach $sections as $sectionItem }
    {if eq( $sectionItem.id, $object.section_id )}
        {set $currentSectionName=$sectionItem.name}
    {/if}
{/foreach}

<h3>{"Section"|i18n( 'design/admin/node/view/full' )}: {$currentSectionName|wash} [{count($sections)}]</h3>
{undef $currentSectionName}

{* DESIGN: Header END *}

{* DESIGN: Content START *}
<div class="box-content">

    {* show the section selector *}
    <label for="SelectedSectionId">{'Choose section'|i18n( 'design/admin/node/view/full' )}:</label>
    <select class="form-control input-sm" id="SelectedSectionId" name="SelectedSectionId"{if $object_is_draft|not()} disabled="disabled"{/if}>
    {foreach $sections as $section}
        {if eq( $section.id, $object.section_id )}
        <option value="{$section.id}" selected="selected">{$section.name|wash}</option>
        {else}
        <option value="{$section.id}">{$section.name|wash}</option>
        {/if}
    {/foreach}
    </select>

    {if $object_is_draft}
        <input type="submit" value="{'Set'|i18n( 'design/admin/node/view/full' )}" name="SectionEditButton" class="btn btn-default btn-sm" />
    {else}
        <input type="submit" value="{'Set'|i18n( 'design/admin/node/view/full' )}" name="SectionEditButton" class="btn btn-default btn-sm" disabled="disabled" title="{'This action is not available in edit view when content object is published!'|i18n('design/admin/content/edit')}" />
    {/if}
    {* DESIGN: Content END *}
</div>


