{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="form-inline">
    <label>{$attribute.content.name|wash}:</label>
    <select class="form-control" name="eZOption[{$attribute.id}]">
        {section var=Options loop=$attribute.content.option_list}
            <option value="{$Options.item.id}">{$Options.item.value|wash}</option>
        {/section}
    </select>
</div>
