{* DO NOT EDIT THIS FILE! Use an override template instead. *}
    <input type="hidden" name="CreatorItemID" value="{$creator.id|wash}" />
    <input type="hidden" name="CreatorStepID" value="{$current_step.id|wash}" />
    <input type="hidden" name="PackageStep" value="1" />




{* DESIGN: Header START *}<div class="box-header">
    <h1 class="context-title">
    {'Package wizard: %wizardname'|i18n( 'design/admin/package',, hash( '%wizardname', $creator.name|wash ) )}
    </h1>

    {* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div>

    <h2>{$current_step.name|wash}</h2>
