services:
    netgen_admin_ui.event_listener.set_tags_admin_pagelayout:
        class: Netgen\Bundle\AdminUIBundle\EventListener\SetTagsAdminPageLayoutListener
        # public: false
        arguments:
            - "@netgen_tags.templating.admin_global_variable"
            - "@ibexa.config.resolver"
            - "%netgen_admin_ui.tags.pagelayout%"
        tags:
            - { name: kernel.event_subscriber }
