services:
    netgen_admin_ui.event_listener.set_information_collection_admin_pagelayout:
        class: Netgen\Bundle\AdminUIBundle\EventListener\SetInformationCollectionAdminPageLayoutListener
        # public: false
        arguments:
            - "@netgen_information_collection.templating.admin_global_variable"
            - "@ibexa.config.resolver"
            - "%netgen_admin_ui.information_collection.pagelayout%"
        tags:
            - { name: kernel.event_subscriber }
