{* DO NOT EDIT THIS FILE! Use an override template instead. *}
    {section show=$error_list}
    <div class="alert alert-warning" role="alert">
        <h2><span class="time">[{currentdate()|l10n( shortdatetime )}]</span> {'Error'|i18n('design/admin/package')}</h2>
        <ul>
            {section var=error loop=$error_list}
                <li>{$error.description|wash}</li>
            {/section}
        </ul>
    </div>
    {/section}

{* DESIGN: Header START *}<div class="box-header">

    <h1 class="context-title">{'Upload package'|i18n('design/admin/package')}</h1>

    {* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div>

{* DESIGN: Content START *}
<div class="box-content panel">

    <form enctype="multipart/form-data" method="post" action={'package/upload'|ezurl}>

        <p>{'Select the file containing the package then click the upload button'|i18n('design/admin/package')}</p>
        <div class="block">
            <input type="hidden" name="MAX_FILE_SIZE" value="512000000" />
            <input name="PackageBinaryFile" type="file" />
        </div>
        {* DESIGN: Content END *}

        <div class="controlbar">
        {* DESIGN: Control bar START *}

            <input class="btn btn-primary" type="submit" name="UploadPackageButton" value="{'Import package'|i18n('design/admin/package')}" />
            <input class="btn btn-default" type="submit" name="UploadCancelButton" value="{'Cancel'|i18n('design/admin/package')}" />
        </div>

    </form>
    {* DESIGN: Control bar END *}
</div>
