{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{def $class_list_by_group = hash()}
{def $class_list = fetch( class, list_by_groups, hash( group_filter, false() ) )}

{foreach $class_list as $class}
    {if is_set( $class_list_by_group[$class.ingroup_list.0.group_name] )}
        {set $class_list_by_group = $class_list_by_group|merge( hash( $class.ingroup_list.0.group_name, $class_list_by_group[$class.ingroup_list.0.group_name]|append( $class ) ) )}
    {else}
        {set $class_list_by_group = $class_list_by_group|merge( hash( $class.ingroup_list.0.group_name, array( $class ) ) )}
    {/if}
{/foreach}

<div id="package" class="create">
    <div id="sid-{$current_step.id|wash}" class="pc-{$creator.id|wash} panel">

        <form method="post" action={'package/create'|ezurl}>

            {include uri="design:package/create/error.tpl"}

            {include uri="design:package/header.tpl"}

            <p>{'Please choose the content classes you want to be included in the package.'|i18n('design/standard/package')}</p>

            <div class="form-inline">
                <div class="form-group">
                    <label>{'Class list'|i18n('design/standard/package')}</label>
                </div>
                <div class="form-group">
                    <select class="listbox form-control" name="ClassList[]" multiple="multiple" size="">
                    {foreach $class_list_by_group as $group_name => $group_classes}
                        <option disabled="disabled" value="group_{$group_name|wash}">{$group_name|wash}</option>
                        {foreach $group_classes as $class}
                            <option value="{$class.id}">&nbsp;&nbsp;&nbsp;{$class.name|wash}</option>
                        {/foreach}
                    {/foreach}
                    </select>
                </div>
            </div>

            {include uri="design:package/navigator.tpl"}

        </form>

    </div>
</div>
<script>
    const listBoxMultiple = document.getElementsByClassName('listbox')[0];
    listBoxMultiple.setAttribute('size', listBoxMultiple.children.length < 30 ? listBoxMultiple.children.length : 30);
</script>
{undef $class_list_by_group $class_list}
