services:
    netgen_admin_ui.layouts.form.layout_wizard:
        class: Netgen\Bundle\AdminUIBundle\Form\Type\LayoutWizardType
        arguments:
            - "@netgen_layouts.api.service.layout"
            - "@netgen_layouts.layout.registry.layout_type"
            - "%netgen_admin_ui.layouts.is_enterprise%"
        tags:
            - { name: form.type }
