parameters:
    netgen_admin_ui.layouts.create_content_route_matcher.siteaccesses: [ngadminui]

services:
    netgen_admin_ui.layouts.related_layouts_loader:
        class: Netgen\Bundle\AdminUIBundle\Layouts\RelatedLayoutsLoader
        public: false
        arguments:
            - "@netgen_layouts.api.service.layout"
            - "@database_connection"

    netgen_admin_ui.layouts.create_content_route_matcher:
        class: Netgen\Bundle\AdminUIBundle\Layouts\CreateContentRouteMatcher
        decorates: router
        public: false
        arguments:
            - "@netgen_admin_ui.layouts.create_content_route_matcher.inner"
            - "%netgen_admin_ui.layouts.create_content_route_matcher.siteaccesses%"

    netgen_admin_ui.layouts.menu_plugin:
        class: Netgen\Bundle\AdminUIBundle\Layouts\MenuPlugin
        public: false
        arguments:
            - "@security.authorization_checker"
        tags:
            - { name: netgen_admin_ui.menu_plugin, priority: -5 }

    netgen_admin_ui.layouts.event_listener.set_admin_pagelayout:
        class: Netgen\Bundle\AdminUIBundle\Layouts\EventListener\SetAdminPageLayoutListener
        public: true
        arguments:
            - "%netgen_admin_ui.layouts.pagelayout%"
        # Using siteaccess aware config, so we need the lazy flag
        lazy: true
        calls:
            - [setIsAdminSiteAccess, ["$is_admin_ui_siteaccess;netgen_admin_ui$"]]
        tags:
            - { name: kernel.event_subscriber }

    netgen_admin_ui.layouts.event_listener.cache_enabled_listener:
        class: Netgen\Bundle\AdminUIBundle\Layouts\EventListener\CacheEnabledListener
        public: true
        arguments:
            - "@netgen_layouts.http_cache.client"
        tags:
            - { name: kernel.event_subscriber }

    netgen_admin_ui.layouts.event_listener.is_enterprise_version:
        class: Netgen\Bundle\AdminUIBundle\Layouts\EventListener\IsEnterpriseVersionListener
        public: true
        arguments:
            - "%netgen_admin_ui.layouts.is_enterprise%"
        tags:
            - { name: kernel.event_subscriber }
