{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block form-inline">
<label>{'Option set name'|i18n( 'design/standard/content/datatype' )}:</label>
<span>{$attribute.content.name|wash}</span>
</div>

{section var=Multioptions loop=$attribute.content.multioption_list}
<div class="block form-inline">
<label>{$Multioptions.item.name|wash}:</label>
<select name="eZOption[{$attribute.id}][]" class="form-control">
    {section var=Option loop=$Multioptions.item.optionlist}
            {if ne( $Option.item.additional_price, '' )}
                {if eq( sum( $Option.index, 1 ), $Multioptions.item.default_option_id )}
                    <option value="{$Option.item.option_id}" selected="selected">{$Option.item.value|wash}-{$Option.item.additional_price|l10n( currency )}</option>
                {else}
                    <option value="{$Option.item.option_id}">{$Option.item.value|wash}-{$Option.item.additional_price|l10n( currency )}</option>
                {/if}
            {else}
                {if eq(sum($Option.index,1), $Multioptions.item.default_option_id)}
                    <option value="{$Option.item.option_id}" selected="selected">{$Option.item.value|wash}</option>
                {else}
                    <option value="{$Option.item.option_id}">{$Option.item.value|wash}</option>
                {/if}
            {/if}
        {/section}
    </select>
</div>
{/section}