{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let class_list=fetch( class, list )}
<div id="package" class="create">
    <div id="sid-{$current_step.id|wash}" class="pc-{$creator.id|wash} panel">
        <div class="row">
            <div class="col-sm-6 col-lg-4">

                <form enctype="multipart/form-data" method="post" action={'package/create'|ezurl}>

                {include uri="design:package/create/error.tpl"}

                {include uri="design:package/header.tpl"}
                <div class="form-group">
                    <p>{'Please select the site CSS file to be included in the package.'|i18n('design/admin/package')}</p>

                    <input type="hidden" name="MAX_FILE_SIZE" value="32000000" />
                    <input class="box form-control" name="PackageSiteCSSFile" type="file" />
                </div>

                <div class="form-group">
                    <p>{'Please select the classes CSS file to be included in the package.'|i18n('design/admin/package')}</p>

                    <input type="hidden" name="MAX_FILE_SIZE" value="32000000" />
                    <input class="box form-control" name="PackageClassesCSSFile" type="file" />
                </div>

                {include uri="design:package/navigator.tpl"}

                </form>
            </div>
        </div>

    </div>
</div>
{/let}
