{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="form-group form-inline">
    <label>{'Default value'|i18n( 'design/standard/class/datatype' )}:</label>
    <input type="text" class="form-control" name="ContentClass_ezfloat_default_value_{$class_attribute.id}" value="{$class_attribute.data_float3|l10n(number)}" size="8" maxlength="20" />
</div>

<div class="block form-inline">
    {switch name=input_state match=$class_attribute.data_float4}
        {case match=1}
            <div class="form-group">
                <label>{'Min float value'|i18n( 'design/standard/class/datatype' )}:</label>
                <input type="text" class="form-control" name="ContentClass_ezfloat_min_float_value_{$class_attribute.id}" value="{$class_attribute.data_float1|l10n(number)}" size="8" maxlength="20" />
            </div>
            <div class="form-group">
                <label>{'Max float value'|i18n( 'design/standard/class/datatype' )}:</label>
                <input type="text" class="form-control" name="ContentClass_ezfloat_max_float_value_{$class_attribute.id}" value="" size="8" maxlength="20" />
            </div>
        {/case}
        {case match=2}
            <div class="form-group">
                <label>{'Min float value'|i18n( 'design/standard/class/datatype' )}:</label>
                <input type="text" class="form-control" name="ContentClass_ezfloat_min_float_value_{$class_attribute.id}" value="" size="8" maxlength="20" />
            </div>
            <div class="form-group">
                <label>{'Max float value'|i18n( 'design/standard/class/datatype' )}:</label>
                <input type="text" class="form-control" name="ContentClass_ezfloat_max_float_value_{$class_attribute.id}" value="{$class_attribute.data_float2|l10n(number)}" size="8" maxlength="20" />
            </div>
        {/case}
        {case match=3}
            <div class="form-group">
                <label>{'Min float value'|i18n( 'design/standard/class/datatype' )}:</label>
                <input type="text" class="form-control" name="ContentClass_ezfloat_min_float_value_{$class_attribute.id}" value="{$class_attribute.data_float1|l10n(number)}" size="8" maxlength="20" />
            </div>
            <div class="form-group">
                <label>{'Max float value'|i18n( 'design/standard/class/datatype' )}:</label>
                <input type="text" class="form-control" name="ContentClass_ezfloat_max_float_value_{$class_attribute.id}" value="{$class_attribute.data_float2|l10n(number)}" size="8" maxlength="20" />
            </div>
        {/case}
        {case}
            <div class="form-group">
                <label>{'Min float value'|i18n( 'design/standard/class/datatype' )}:</label>
                <input type="text" class="form-control" name="ContentClass_ezfloat_min_float_value_{$class_attribute.id}" value="" size="8" maxlength="20" />
            </div>
            <div class="form-group">
                <label>{'Max float value'|i18n( 'design/standard/class/datatype' )}:</label>
                <input type="text" class="form-control" name="ContentClass_ezfloat_max_float_value_{$class_attribute.id}" value="" size="8" maxlength="20" />
            </div>
        {/case}
    {/switch}
</div>