{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block form-inline">
    <label>{'Max file size'|i18n( 'design/standard/class/datatype ')}:</label>
    <input type="text" class="form-control" name="ContentClass_ezimage_max_filesize_{$class_attribute.id}" value="{$class_attribute.data_int1}" size="5" maxlength="5" />&nbsp;MB
</div>
