{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute'}
{let attribute_content=$attribute.content}

{* Current image. *}
<div class="block file-attribute">
    {if $attribute_content.original.is_valid}
        <div class="table">
            <div class="cell cell-image">
                {attribute_view_gui image_class=ezini( 'ImageSettings', 'DefaultEditAlias', 'content.ini' ) attribute=$attribute}
            </div>
            <div class="cell">
                <ul class="details">
                    <li><label>{'Current image'|i18n( 'design/standard/content/datatype' )}:</label><span>{$attribute.content.original.original_filename|wash( xhtml )}</span></li>
                    <li><label>{'MIME type'|i18n( 'design/standard/content/datatype' )}:</label><span>{$attribute.content.original.mime_type|wash( xhtml )}</span></li>
                    <li><label>{'Size'|i18n( 'design/standard/content/datatype' )}:</label><span>{$attribute.content.original.filesize|si( byte )}</span></li>
                    <li><label>{'Dimensions'|i18n( 'design/standard/content/datatype' )}:</label><span>{$attribute.content.original.width} x {$attribute.content.original.height} px</span></li>
                </ul>
            </div>
        </div>
    {else}
        <p>{'There is no image file.'|i18n( 'design/standard/content/datatype' )}</p>
    {/if}

    {if $attribute_content.original.is_valid}
        <input class="btn btn-default" type="submit" name="CustomActionButton[{$attribute.id}_delete_image]" value="{'Remove image'|i18n( 'design/standard/content/datatype' )}" />
    {/if}
</div>

{* New image file for upload. *}
<div class="row">
    <div class="col-sm-6">
        <input type="hidden" name="MAX_FILE_SIZE" value="{$attribute.contentclass_attribute.data_int1|mul( 1024, 1024 )}" />
        <label for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_file">{'New image file for upload'|i18n( 'design/standard/content/datatype' )}:</label>
        <div class="input-group">
            <span class="input-group-btn">
                <span class="btn btn-primary btn-file">
                    Browse&hellip; <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_file" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_imagename_{$attribute.id}" type="file" />
                </span>
            </span>
            <input type="text" class="form-control" readonly>
        </div>
    </div>

    {* Alternative image text. *}
    <div class="col-sm-6">
        <label for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_alttext">{'Alternative image text'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_alttext" class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_imagealttext_{$attribute.id}" type="text" value="{$attribute_content.alternative_text|wash(xhtml)}" />
    </div>
</div>
{/let}
{/default}


